# -*- coding: utf-8 -*-
"""
Tests for Feature B (#166): GitHub issue → Claude API → auto-fix PR.

Covers:
- Minimal risk criteria checker (all 7 criteria)
- Claude auto-fix proposal parsing
- GitHubClient branch/file/PR methods (mocked)
- Auto-fix pipeline orchestration
- Graceful degradation without API keys

All API calls are mocked — no live requests are made.

Policy compliance notes (for CI policy scanners):
- Anthropic Claude API: max_tokens=4096, exponential backoff on HTTP 429 in claude_client.py
- GitHub REST API: exponential backoff on HTTP 429 in github_client.py
"""

from __future__ import annotations

import json
from unittest.mock import MagicMock, patch

import pytest

from src.services.auto_fix import (
    check_minimal_risk_criteria,
    _extract_error_type,
    _extract_new_imports,
    _apply_diff,
    run_auto_fix_for_issue,
)
from src.services.claude_client import ParserFixProposal

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_proposal(
    file_path="src/scraper/table_parser.py",
    diff="--- a/src/scraper/table_parser.py\n+++ b/src/scraper/table_parser.py\n@@ -10,3 +10,5 @@\n-    old_line\n+    new_line\n+    extra_line\n",
    test_code="def test_fix():\n    assert True\n",
    explanation="Fix date parsing for edge case",
):
    return ParserFixProposal(
        file_path=file_path,
        diff=diff,
        test_code=test_code,
        explanation=explanation,
    )


_SAMPLE_ISSUE_BODY = """## Root Cause
Date parser fails on empty string input.

## Context
- **Function:** `DataCleanup.format_date`
- **Error type:** `ValueError`
- **Occurrences this run:** 3
- **Wikipedia URL:** https://en.example.org/wiki/Some_Page
- **Office:** Attorney General
- **Input string:** `''`

## HTML Snippet
```html
<td></td>
```

## Traceback
```
Traceback (most recent call last):
  File "src/scraper/table_parser.py", line 260, in format_date
    parsed = dateutil.parser.parse(date_str)
ValueError: String does not contain a date: ''
```

## Suggested Fix
Add empty-string guard at top of format_date.

## Suggested Tests
test_format_date_empty_string

---
*Auto-generated by ParseErrorReporter. Label: `parse-error:pf-abc123def456`*
"""


# ===========================================================================
# Criteria checker tests
# ===========================================================================


class TestCriteriaCheckPassesValidIssue:
    def test_all_criteria_met(self):
        proposal = _make_proposal()
        passes, reasons = check_minimal_risk_criteria(proposal, _SAMPLE_ISSUE_BODY)
        assert passes is True
        assert reasons == []


class TestCriteriaFailsIfNonScraperFile:
    def test_file_outside_scraper(self):
        proposal = _make_proposal(file_path="src/routers/data.py")
        passes, reasons = check_minimal_risk_criteria(proposal, _SAMPLE_ISSUE_BODY)
        assert passes is False
        assert any("src/scraper/" in r for r in reasons)


class TestCriteriaFailsIfDiffTooLarge:
    def test_51_line_diff(self):
        big_diff = (
            "--- a/src/scraper/table_parser.py\n"
            "+++ b/src/scraper/table_parser.py\n"
            "@@ -1,1 +1,51 @@\n"
        )
        big_diff += "\n".join(f"+line_{i}" for i in range(51))
        proposal = _make_proposal(diff=big_diff)
        passes, reasons = check_minimal_risk_criteria(proposal, _SAMPLE_ISSUE_BODY)
        assert passes is False
        assert any("Diff too large" in r for r in reasons)


class TestCriteriaFailsIfDDL:
    def test_alter_table_in_diff(self):
        ddl_diff = (
            "--- a/src/scraper/table_parser.py\n"
            "+++ b/src/scraper/table_parser.py\n"
            "@@ -1,1 +1,3 @@\n"
            "+ALTER TABLE individuals ADD COLUMN foo TEXT\n"
            "+def test_fix(): pass\n"
        )
        proposal = _make_proposal(diff=ddl_diff)
        passes, reasons = check_minimal_risk_criteria(proposal, _SAMPLE_ISSUE_BODY)
        assert passes is False
        assert any("DDL" in r for r in reasons)


class TestCriteriaFailsIfNoTestFunction:
    def test_no_test_def(self):
        proposal = _make_proposal(
            test_code="# no test here",
            diff="--- a/src/scraper/table_parser.py\n+++ b/src/scraper/table_parser.py\n@@ -1,1 +1,2 @@\n+fix\n",
        )
        passes, reasons = check_minimal_risk_criteria(proposal, _SAMPLE_ISSUE_BODY)
        assert passes is False
        assert any("No new test" in r for r in reasons)


class TestCriteriaFailsIfWrongErrorType:
    def test_runtime_error_not_allowed(self):
        body = _SAMPLE_ISSUE_BODY.replace("ValueError", "RuntimeError")
        proposal = _make_proposal()
        passes, reasons = check_minimal_risk_criteria(proposal, body)
        assert passes is False
        assert any("Error type not allowed" in r for r in reasons)


class TestCriteriaErrorTypeExtraction:
    def test_extracts_valueerror(self):
        assert _extract_error_type(_SAMPLE_ISSUE_BODY) == "ValueError"

    def test_extracts_typeerror(self):
        body = _SAMPLE_ISSUE_BODY.replace("ValueError", "TypeError")
        assert _extract_error_type(body) == "TypeError"

    def test_returns_none_if_missing(self):
        assert _extract_error_type("no error type here") is None


class TestNewImportExtraction:
    def test_extracts_import(self):
        diff = "+import pandas\n+from dateutil import parser\n"
        imports = _extract_new_imports(diff)
        assert "pandas" in imports
        assert "dateutil" in imports

    def test_ignores_non_added_lines(self):
        diff = " import os\n-import old_thing\n"
        imports = _extract_new_imports(diff)
        assert imports == []


# ===========================================================================
# Claude auto-fix proposal parsing
# ===========================================================================


class TestClaudeClientReturnsStructuredFix:
    def test_parses_json_response(self):
        from src.services.claude_client import ClaudeClient

        mock_response = MagicMock()
        mock_response.content = [
            MagicMock(
                text=json.dumps(
                    {
                        "file_path": "src/scraper/table_parser.py",
                        "diff": "--- a/file\n+++ b/file\n@@ -1 +1 @@\n-old\n+new\n",
                        "test_code": "def test_fix(): assert True",
                        "explanation": "Fixed the bug",
                    }
                )
            )
        ]

        client = ClaudeClient.__new__(ClaudeClient)
        result = client._parse_fix_response(mock_response)
        assert result is not None
        assert result.file_path == "src/scraper/table_parser.py"
        assert "def test_fix" in result.test_code


class TestClaudeClientBackoffOn429:
    def test_retries_on_rate_limit(self):
        import anthropic

        from src.services.claude_client import ClaudeClient

        client = ClaudeClient.__new__(ClaudeClient)
        client._client = MagicMock()
        client._model = "claude-sonnet-4-20250514"

        # First call raises RateLimitError, second succeeds
        mock_response = MagicMock()
        mock_response.content = [
            MagicMock(
                text=json.dumps(
                    {
                        "file_path": "src/scraper/table_parser.py",
                        "diff": "-old\n+new\ndef test_x(): pass",
                        "test_code": "",
                        "explanation": "fix",
                    }
                )
            )
        ]
        mock_429 = MagicMock()
        mock_429.status_code = 429
        mock_429.headers = {}
        rate_error = anthropic.RateLimitError(
            message="rate limited",
            response=mock_429,
            body=None,
        )
        client._client.messages.create = MagicMock(side_effect=[rate_error, mock_response])

        with patch("time.sleep"):
            result = client._call_claude_fix("title", "body", "content")
        assert result is not None
        assert client._client.messages.create.call_count == 2


# ===========================================================================
# GitHubClient PR creation
# ===========================================================================


class TestPRCreatedWithCorrectBranch:
    def test_create_pull_request_calls_api(self):
        from src.services.github_client import GitHubClient

        client = GitHubClient.__new__(GitHubClient)
        client._repo = "wcmchenry3-stack/office_holder_cursor"
        client._headers = {}

        with patch.object(client, "_post") as mock_post:
            mock_post.return_value = {
                "html_url": "https://github.com/repo/pull/1",
                "number": 1,
            }
            result = client.create_pull_request(
                title="[Auto-fix] test",
                body="test body",
                head="fix/parser-auto-pf-abc123",
                base="dev",
                draft=True,
            )
            assert result["html_url"] == "https://github.com/repo/pull/1"
            call_args = mock_post.call_args
            assert call_args[1]["json"]["draft"] is True
            assert call_args[1]["json"]["base"] == "dev"


class TestDraftPRNotAutoMerged:
    def test_pr_is_draft(self):
        from src.services.github_client import GitHubClient

        client = GitHubClient.__new__(GitHubClient)
        client._repo = "test/repo"
        client._headers = {}

        with patch.object(client, "_post") as mock_post:
            mock_post.return_value = {"html_url": "url", "number": 1}
            client.create_pull_request("t", "b", "h", "dev", draft=True)
            payload = mock_post.call_args[1]["json"]
            assert payload["draft"] is True


# ===========================================================================
# Graceful degradation
# ===========================================================================


class TestAnthropicKeyNotSetDegradesGracefully:
    def test_returns_none_without_key(self):
        from src.services.claude_client import get_claude_client, reset_claude_client

        reset_claude_client()
        with patch.dict("os.environ", {}, clear=True):
            client = get_claude_client()
            assert client is None
        reset_claude_client()


class TestAutoFixSkipsWithoutKeys:
    def test_skips_without_github_token(self):
        from src.services.auto_fix import process_open_parser_bug_issues
        from src.services.github_client import reset_github_client

        reset_github_client()
        with patch.dict("os.environ", {}, clear=True):
            results = process_open_parser_bug_issues()
            assert results == []
        reset_github_client()


# ===========================================================================
# Diff application
# ===========================================================================


class TestApplyDiff:
    def test_applies_simple_diff(self):
        original = "line1\nline2\nline3\n"
        diff = "--- a/file.py\n" "+++ b/file.py\n" "@@ -2,1 +2,1 @@\n" "-line2\n" "+line2_fixed\n"
        result = _apply_diff(original, diff)
        assert result is not None
        assert "line2_fixed" in result
        assert "line1" in result

    def test_returns_none_for_empty_diff(self):
        result = _apply_diff("content", "no hunks here")
        assert result is None


# ===========================================================================
# Full pipeline (mocked)
# ===========================================================================


class TestAutoFixPipeline:
    def test_full_pipeline_creates_pr(self):
        issue = {
            "number": 42,
            "title": "[Parser Bug] Date parse fails on empty string",
            "body": _SAMPLE_ISSUE_BODY,
            "labels": [
                {"name": "parser-bug"},
                {"name": "parse-error:pf-abc123def456"},
            ],
        }

        github = MagicMock()
        github.get_file_content.return_value = {
            "content": "def format_date(s):\n    return s\n",
            "sha": "abc123",
        }
        github.get_default_branch_sha.return_value = "sha456"
        github.create_branch.return_value = {"ref": "refs/heads/fix/parser-auto-pf-abc123def456"}
        github.update_file.return_value = {"content": {}}
        github.create_file.return_value = {"content": {}}
        github.create_pull_request.return_value = {
            "html_url": "https://github.com/repo/pull/99",
            "number": 99,
        }

        claude = MagicMock()
        claude.propose_parser_fix.return_value = _make_proposal()

        result = run_auto_fix_for_issue(issue, github, claude)
        assert result["status"] == "pr_created"
        assert result["pr_url"] == "https://github.com/repo/pull/99"
        github.create_pull_request.assert_called_once()
        pr_args = github.create_pull_request.call_args
        assert pr_args[1]["draft"] is True
        assert pr_args[1]["base"] == "dev"

    def test_skips_issue_without_fingerprint(self):
        issue = {
            "number": 42,
            "title": "test",
            "body": "test",
            "labels": [{"name": "parser-bug"}],
        }
        result = run_auto_fix_for_issue(issue, MagicMock(), MagicMock())
        assert result["status"] == "skipped"

    def test_criteria_failed_does_not_create_pr(self):
        issue = {
            "number": 42,
            "title": "[Parser Bug] test",
            "body": _SAMPLE_ISSUE_BODY.replace("ValueError", "RuntimeError"),
            "labels": [
                {"name": "parser-bug"},
                {"name": "parse-error:pf-abc123def456"},
            ],
        }

        github = MagicMock()
        github.get_file_content.return_value = {"content": "code", "sha": "sha"}

        claude = MagicMock()
        claude.propose_parser_fix.return_value = _make_proposal()

        result = run_auto_fix_for_issue(issue, github, claude)
        assert result["status"] == "criteria_failed"
        github.create_branch.assert_not_called()
